# Generated by Django 5.0 on 2023-12-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name': 'Поставка', 'verbose_name_plural': 'Поставки'},
        ),
    ]
