# Generated by Django 5.0 on 2023-12-26 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_product_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.supplier', verbose_name='Поставщик'),
        ),
    ]
