# Generated by Django 5.0 on 2023-12-26 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_supply_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_recipient', to='network.supplier', verbose_name='Получатель поставки'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_supplier', to='network.supplier', verbose_name='Поставщик'),
        ),
    ]
